// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njyinvaswcchoyvnbdvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qeWludmFzd2NjaG95dm5iZHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExOTE4NTgsImV4cCI6MjA2Njc2Nzg1OH0.j7BvYkgKIOeBMVD1xGhI4RWZkKBms4HjRtA1UjlCRLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);